---
swagger: "2.0"

info:
  description: "Image analyzer service for anchore-engine"
  version: "0.9.0"
  title: "Image Analyzer"
  contact:
    email: "dev@anchore.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

#host: "localhost:83"

basePath: "/"

tags:
- name: "analyzer"
  description: "Image Analyzer"
  externalDocs:
    description: "Find out more"
    url: "http://anchore.com"

schemes:
- "https"
- "http"

paths:
  /health:
    get:
      x-swagger-router-controller: anchore_engine.apis.common
      operationId: health_check
      x-anchore-authz-action: None
      description: Health check, returns 200 and no body if service is running
      responses:
        200:
          description: Empty body on success
  /version:
    get:
      x-swagger-router-controller: anchore_engine.apis.common
      operationId: version_check
      x-anchore-authz-action: None
      description: Returns the version object for the service, including db schema version info
      responses:
        200:
          description: Version object describing version state
          schema:
            $ref: "#/definitions/ServiceVersion"
  /status:
    get:
      tags:
      - "analyzer"
      summary: "Get the status of the service"
      description: ""
      operationId: "status"
      produces:
      - "application/json"
      responses:
        200:
          description: "service status"
          schema:
            type: object
      x-swagger-router-controller: "anchore_engine.services.analyzer.api.controllers.default_controller"
definitions:
  ServiceVersion:
    type: object
    description: Version information for a service
    properties:
      service:
        type: object
        properties:
          version:
            type: string
            description: Semantic Version string of the service implementation
      api:
        type: object
        description: Api Version string
        properties:
          version:
            type: string
            description: Semantic version of the api
      db:
        type: object
        properties:
          schema_version:
            type: string
            description: Semantic version of the db schema
