name: Lint Python Code Using Black
on:
  push:
    branches-ignore:
      - publish-docs
  pull_request:
    branches-ignore:
      - publish-docs
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@20.8b1
